name: Open Journals Publishing Artifacts
description: Create PDF and JATS files for an Open Journals paper
inputs:
  journal:
    description: Target journal, must be either "joss" or "jose"
    required: false
    default: joss
  paper-path:
    description: >-
        Path to the main paper Markdown file, relative to the
        project's root directory.
    required: false
    default: 'paper.md'
  metadata-file:
    description: >-
        Path to the metadata file to use to compile the paper
    required: false
    default: ''
runs:
  using: docker
  image: 'docker://openjournals/inara:latest'
  env:
    GIT_SHA: $GITHUB_SHA
    JOURNAL: ${{ inputs.journal }}
  args:
    - ${{ inputs.paper-path }}
    - "-m ${{ inputs.metadata-file }}"
branding:
  icon: file-text
  color: blue
