name: NeuroLibre Summary PDF Actions
description: Create PDF and XML files for a NeuroLibre preprint
inputs:
  journal:
    description: Target journal, set to "neurolibre"
    required: false
    default: neurolibre
  paper-path:
    description: >-
        Path to the main paper Markdown file, relative to the
        project's root directory.
    required: false
    default: 'paper.md'
  args:
    description: |
      Arguments to be passed to the neurolibre/inara
      Options:
        -m ARTICLE_INFO_FILE    path to the article's metadata info file
        -o OUTPUT_FORMATS       output formats (html/pdf/jats/crossref)
    required: false
    default: ''
runs:
  using: docker
  image: 'docker://neurolibre/inara:latest'
  env:
    GIT_SHA: $GITHUB_SHA
    JOURNAL: ${{ inputs.journal }}
  args:
    - ${{ inputs.args }}
    - ${{ inputs.paper-path }}
branding:
  icon: file-text
  color: red
